### ISSUE TITLE
add createReactClass for React v16

### ISSUE THREAD

**Issue by c0ldcalamari** [keredson/bottle-react#11]
:wave: :wave: 
```
// Before (15.4 and below)
var React = require('react');

var Component = React.createClass({
  mixins: [MixinA],
  render() {
    return <Child />;
  }
});

// After (15.5)
var React = require('react');
var createReactClass = require('create-react-class');

var Component = createReactClass({
  mixins: [MixinA],
  render() {
    return <Child />;
  }
});
```

**Comment by keredson** [comment]
it says that `React.createClass` is deprecated.  is `create-react-class` a migration workaround or is it the new recommended method?

**Comment by c0ldcalamari** [comment]
`create-react-class` would be our migration work around. 
React recommends we use JS classes but IE does not support JS classes.

https://reactjs.org/blog/2017/09/26/react-v16.0.html

> Packaging
> - There is no react/lib/* and react-dom/lib/* anymore. Even in CommonJS environments, React and ReactDOM are precompiled to single files (“flat bundles”). If you previously relied on undocumented React internals, and they don’t work anymore, let us know about your specific case in a new issue, and we’ll try to figure out a migration strategy for you.

> - There is no react-with-addons.js build anymore. All compatible addons are published separately on npm, and have single-file browser versions if you need them.

> - The deprecations introduced in 15.x have been removed from the core package. React.createClass is now available as create-react-class, React.PropTypes as prop-types, React.DOM as react-dom-factories, react-addons-test-utils as react-dom/test-utils, and shallow renderer as react-test-renderer/shallow. See 15.5.0 and 15.6.0 blog posts for instructions on migrating code and automated codemods.

> - The names and paths to the single-file browser builds have changed to emphasize the difference between development and production builds. For example:

> - react/dist/react.js → react/umd/react.development.js
> - react/dist/react.min.js → react/umd/react.production.min.js
> - react-dom/dist/react-dom.js → react-dom/umd/react-dom.development.js
> - react-dom/dist/react-dom.min.js → react-dom/umd/react-dom.production.min.js
