### ISSUE TITLE
Support OSX out of the box

### ISSUE THREAD

**Issue by logannc** [keredson/bottle-react#24]
```
libc = ctypes.CDLL("libc.so.6")
```

Can fail on some (many?) installations of OSX because Apple doesn't use that name for their libc, they use `libSystem.dylib`.

**Comment by keredson** [comment]
i have no way of testing.  can you test something like:
```
try:
  libc = ctypes.CDLL("libc.so.6")
except:
  libc = ctypes.CDLL("libSystem.dylib")
```

for me?  (w/ a better exception catch)
