### ISSUE TITLE
Directory JSX Not fOund

### ISSUE THREAD

**Issue by Terron23** [keredson/bottle-react#28]
I am recieving the following error:  raise Exception('Directory %s not found - please create it or set the jsx_path                                           parameter.' % repr(self.jsx_path))
Exception: Directory 'jsx' not found - please create it or set the jsx_path parame                                          ter.

**Comment by keredson** [comment]
You need a directory `jsx` which holds your jsx files.

**Comment by Terron23** [comment]
Thank you
